import os
import time


os.system("clear")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
os.system("figlet Mami Zeka")
os.system("clear")
print("yükleniyor...")
time.sleep(2)
os.system("pip install fuzzywuzzy")
os.system("clear")
print("yükleniyor...")
time.sleep(2)
os.system("pkg install figlet -y")
os.system("clear")
print("yükleniyor...")
time.sleep(2)
os.system("clear")
print("yükleniyor...")
time.sleep(2)
os.system("pkg install termux-api -y ")
os.system("clear")
print("yükleniyor...")
time.sleep(2)
os.system("clear")
print("yükleniyor...")
time.sleep(3)
os.system("clear")
print("yükleniyor...")
time.sleep(3)
os.system("clear")
print("yüklenme tamamlandı 2 sn bekle")
time.sleep(2)
os.system("clear")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
os.system("figlet Mami Zeka")
print("")
print("")
print("")
print("python mamizeka.py yazın kodu başlatın")
